export const ADD_TAB = '@USER_COMPONENT_TABS/ADD_TAB'
export const REMOVE_TAB = '@USER_COMPONENT_TABS/REMOVE_TAB'
export const ADD_COMPONENT = '@USER_COMPONENT_TABS/ADD_COMPONENT'
export const IMPORT_TABS = '@USER_COMPONENT_TABS/IMPORT_TABS'
